### ISSUE TITLE
放在SliverPersistentHeader会黑屏，请问如何解决

### ISSUE THREAD

**Issue by Unicellular-SU** [sudosiyang/flutter_aliPlayer#1]
想实现类似哔哩哔哩的效果，播放时固定，暂停时向上滑动隐藏，使用了NestedScrollView，把播放器放到SliverPersistentHeader里，有声音但是黑屏。大致代码如下：
`
/// initState中监听播放状态
_videoController.onStatusEvent.listen((event) {
    setState(() {
        _isPlay = _videoController.isPlaying;
    });
});
/// NestedScrollView中使用SliverPersistentHeader包裹播放器
SliverPersistentHeader(
    delegate: _SliverDelegate(
    minHeight: getScreenWidth() / 16 * 9,
    maxHeight: getScreenWidth() / 16 * 9,
    child: _buildVideoPlayer()),
    pinned: _isPlay,
)
class _SliverDelegate extends SliverPersistentHeaderDelegate {
    _SliverDelegate({
        @required this.minHeight,
        @required this.maxHeight,
        @required this.child,
    });
    final double minHeight; //最小高度
    final double maxHeight; //最大高度
    final Widget child; //孩子
    @override
    double get minExtent => minHeight;
    @override
    double get maxExtent => max(maxHeight, minHeight);
    @override
    Widget build(
        BuildContext context, double shrinkOffset, bool overlapsContent) {
        return new SizedBox.expand(child: child);
    }
    @override //是否需要重建
    bool shouldRebuild(_SliverDelegate oldDelegate) {
        return false; 
    }
}`

**Comment by sudosiyang** [comment]
aliplayer 没提供 获取像素功能 无法使用PixelBuffer进行外接纹理渲染，每次重建后会丢失textureId 故黑屏

android应该为啥问题 
ios会黑屏 已丢失 textureId
